"""Add rendered pages and OCR lines

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-09 00:16:23.301891

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "submission_pages",
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("image_path", sa.String(length=512), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("number > 0", name=op.f("ck_submission_pages_number_positive")),
        sa.CheckConstraint(
            "width > 0 AND height > 0", name=op.f("ck_submission_pages_size_positive")
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_submission_pages_submission_id_submissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submission_pages")),
        sa.UniqueConstraint(
            "submission_id", "number", name="uq_submission_pages_submission_number"
        ),
    )
    op.create_index(
        op.f("ix_submission_pages_submission_id"),
        "submission_pages",
        ["submission_id"],
        unique=False,
    )
    op.create_table(
        "ocr_lines",
        sa.Column("page_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("corrected_text", sa.Text(), nullable=True),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("box", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_ocr_lines_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["submission_pages.id"],
            name=op.f("fk_ocr_lines_page_id_submission_pages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_lines")),
        sa.UniqueConstraint("page_id", "position", name="uq_ocr_lines_page_position"),
    )
    op.create_index(op.f("ix_ocr_lines_page_id"), "ocr_lines", ["page_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ocr_lines_page_id"), table_name="ocr_lines")
    op.drop_table("ocr_lines")
    op.drop_index(op.f("ix_submission_pages_submission_id"), table_name="submission_pages")
    op.drop_table("submission_pages")
    # ### end Alembic commands ###
