"""Add the question paper and questions

The question paper is stored on `assessments` directly (path plus the same
metadata `submissions` keeps for its own PDF), because there is exactly one
per assessment, unlike submissions. `questions` holds what the paper
contains: a teacher-assigned number (text, not assumed numeric) and a
statement, ordered by `position` and unique per assessment on both.

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-09

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position > 0", name=op.f("ck_questions_position_positive")),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_questions_assessment_id_assessments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint("assessment_id", "number", name="uq_questions_assessment_number"),
        sa.UniqueConstraint("assessment_id", "position", name="uq_questions_assessment_position"),
    )
    op.create_index(
        op.f("ix_questions_assessment_id"), "questions", ["assessment_id"], unique=False
    )
    op.add_column(
        "assessments", sa.Column("question_paper_path", sa.String(length=512), nullable=True)
    )
    op.add_column(
        "assessments",
        sa.Column("question_paper_original_filename", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "assessments", sa.Column("question_paper_file_size_bytes", sa.Integer(), nullable=True)
    )
    op.add_column(
        "assessments", sa.Column("question_paper_page_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "assessments",
        sa.Column("question_paper_checksum_sha256", sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assessments", "question_paper_checksum_sha256")
    op.drop_column("assessments", "question_paper_page_count")
    op.drop_column("assessments", "question_paper_file_size_bytes")
    op.drop_column("assessments", "question_paper_original_filename")
    op.drop_column("assessments", "question_paper_path")
    op.drop_index(op.f("ix_questions_assessment_id"), table_name="questions")
    op.drop_table("questions")
    # ### end Alembic commands ###
